version: 2.1
orbs:
  codecov: codecov/codecov@1.1.3

jobs:
  build:
    docker:
      - image: rust:latest
    environment:
      TZ: "/usr/share/zoneinfo/Canada/Eastern"
    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Stable Build
          command: cargo build
      - run:
          name: Test
          command: cargo test
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"
